facebook:
  client:
    clientId: 2325392537693621
    clientSecret: 1dd6229294a3f7baccb0b5727af94760
    accessTokenUri: https://grahp.facebook.com/oauth/access_token
    userAutorizationUri: https://www,facebook.com/dialog/oauth?display=popup
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
    scope: email
  resource:
    userInfoUri: https://graph.facebook.com/me?fields=id,name,email,link

google:
  client:
    clientId: 230000545803-kpe6ukhdgof4pmsfs9rg7dub7i7lcm3d.apps.googleusercontent.com
    clientSecret: BMeBn1IDIeXo-9c2yXFPsgnV
    accessTokenUri: https://accounts.google.com/o/oaut2/token
    userAutorizationUri: https://accounts.google.com/o/oauth2/auth
    scope: email, profile
  resource:
    userInfoUri: https://www.googleapis.com/oauth2/v2/userinfo

kakao:
  client:
    clientId: 4e644de7ff2e07177a71c8646ec05a34
    accessTokenUri: https://kauth.kakao.com/oauth/token
    userAutorizationUri: https://kauth.kakao.com/oauth/authrize
  resource:
    userInfoUri: https://kapi.kakao.com/v1/user/me